[2023-05-15T01:42:26.993+0200] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-05-15T01:42:27.002+0200] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-05-15T01:42:27.002+0200] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-15T01:42:27.016+0200] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract> on 2023-05-12 00:00:00+00:00
[2023-05-15T01:42:27.033+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_news_pipeline', 'extract', 'scheduled__2023-05-12T00:00:00+00:00', '--job-id', '1442', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/var/folders/qv/qkzfd8cs7hdftb0synd9cw3h0000gn/T/tmp3rascgst']
[2023-05-15T01:42:27.036+0200] {standard_task_runner.py:85} INFO - Job 1442: Subtask extract
[2023-05-15T01:42:27.109+0200] {task_command.py:410} INFO - Running <TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [running]> on host niyants-mbp.fritz.box
[2023-05-15T01:42:27.029+0200] {standard_task_runner.py:57} INFO - Started process 7521 to run task
[2023-05-15T01:42:27.266+0200] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_news_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-12T00:00:00+00:00'
[2023-05-15T01:42:27.268+0200] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/niyantmehta/opt/anaconda3/envs/finalvenv/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niyantmehta/opt/anaconda3/envs/finalvenv/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niyantmehta/Spiced/ETL_Pipeline/airflow/ETL_dags/etl_pipeline.py", line 32, in extract
    tokenizer = AutoTokenizer.from_pretrained("/Users/niyantmehta/Spiced/final/tokenizer")
                ^^^^^^^^^^^^^
NameError: name 'AutoTokenizer' is not defined
[2023-05-15T01:42:27.279+0200] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_news_pipeline, task_id=extract, execution_date=20230512T000000, start_date=20230514T234226, end_date=20230514T234227
[2023-05-15T01:42:27.293+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 1442 for task extract (name 'AutoTokenizer' is not defined; 7521)
[2023-05-15T01:42:27.339+0200] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-15T01:42:27.365+0200] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-15T01:43:36.073+0200] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-05-15T01:43:36.087+0200] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-05-15T01:43:36.087+0200] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-15T01:43:36.101+0200] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract> on 2023-05-12 00:00:00+00:00
[2023-05-15T01:43:36.123+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_news_pipeline', 'extract', 'scheduled__2023-05-12T00:00:00+00:00', '--job-id', '1444', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/var/folders/qv/qkzfd8cs7hdftb0synd9cw3h0000gn/T/tmp06ots4gr']
[2023-05-15T01:43:36.127+0200] {standard_task_runner.py:85} INFO - Job 1444: Subtask extract
[2023-05-15T01:43:36.116+0200] {standard_task_runner.py:57} INFO - Started process 7628 to run task
[2023-05-15T01:43:36.197+0200] {task_command.py:410} INFO - Running <TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [running]> on host niyants-mbp.fritz.box
[2023-05-15T01:43:36.264+0200] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_news_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-12T00:00:00+00:00'
[2023-05-15T01:43:36.265+0200] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/niyantmehta/opt/anaconda3/envs/finalvenv/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niyantmehta/opt/anaconda3/envs/finalvenv/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niyantmehta/Spiced/ETL_Pipeline/airflow/ETL_dags/etl_pipeline.py", line 32, in extract
    tokenizer = AutoTokenizer.from_pretrained("/Users/niyantmehta/Spiced/final/tokenizer")
                ^^^^^^^^^^^^^
NameError: name 'AutoTokenizer' is not defined
[2023-05-15T01:43:36.417+0200] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_news_pipeline, task_id=extract, execution_date=20230512T000000, start_date=20230514T234336, end_date=20230514T234336
[2023-05-15T01:43:36.518+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 1444 for task extract (name 'AutoTokenizer' is not defined; 7628)
[2023-05-15T01:43:36.558+0200] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-15T01:43:36.586+0200] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-15T01:45:17.557+0200] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-05-15T01:45:17.565+0200] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2023-05-15T01:45:17.566+0200] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-15T01:45:17.575+0200] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract> on 2023-05-12 00:00:00+00:00
[2023-05-15T01:45:17.590+0200] {standard_task_runner.py:57} INFO - Started process 7749 to run task
[2023-05-15T01:45:17.599+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_news_pipeline', 'extract', 'scheduled__2023-05-12T00:00:00+00:00', '--job-id', '1447', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/var/folders/qv/qkzfd8cs7hdftb0synd9cw3h0000gn/T/tmpt_2139z0']
[2023-05-15T01:45:17.603+0200] {standard_task_runner.py:85} INFO - Job 1447: Subtask extract
[2023-05-15T01:45:17.666+0200] {task_command.py:410} INFO - Running <TaskInstance: etl_news_pipeline.extract scheduled__2023-05-12T00:00:00+00:00 [running]> on host niyants-mbp.fritz.box
[2023-05-15T01:45:17.735+0200] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_news_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-12T00:00:00+00:00'
[2023-05-15T01:45:17.736+0200] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/niyantmehta/opt/anaconda3/envs/finalvenv/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niyantmehta/opt/anaconda3/envs/finalvenv/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niyantmehta/Spiced/ETL_Pipeline/airflow/ETL_dags/etl_pipeline.py", line 32, in extract
    tokenizer = AutoTokenizer.from_pretrained("/Users/niyantmehta/Spiced/final/tokenizer")
                ^^^^^^^^^^^^^
NameError: name 'AutoTokenizer' is not defined
[2023-05-15T01:45:17.748+0200] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_news_pipeline, task_id=extract, execution_date=20230512T000000, start_date=20230514T234517, end_date=20230514T234517
[2023-05-15T01:45:17.756+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 1447 for task extract (name 'AutoTokenizer' is not defined; 7749)
[2023-05-15T01:45:17.780+0200] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-15T01:45:17.806+0200] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
